CREATE TABLE schools (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(100) NOT NULL COMMENT '学校名称',
    code VARCHAR(50) NULL COMMENT '学校代码',
    level VARCHAR(20) NOT NULL COMMENT '学段: 小学/中学/高中',
    province VARCHAR(50) NOT NULL DEFAULT '河南省' COMMENT '省',
    city VARCHAR(50) NOT NULL COMMENT '市',
    county VARCHAR(50) NOT NULL COMMENT '县/区',
    address VARCHAR(255) NULL COMMENT '详细地址',
    phone VARCHAR(20) NULL COMMENT '联系电话',
    intro TEXT NULL COMMENT '校共体详细介绍',
    model TEXT NULL COMMENT '共同体组建模式',
    advantage TEXT NULL COMMENT '核心优势',
    images JSON NULL COMMENT '学校环境图片',
    logo VARCHAR(255) NULL COMMENT '学校Logo',
    background_image VARCHAR(500) NULL COMMENT '页面背景图片URL(示范校共体页面)',
    is_visible TINYINT NOT NULL DEFAULT 1 COMMENT '是否在官网显示: 0-否, 1-是',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0-禁用, 1-启用',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序(升序)',
    created_by BIGINT NULL COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME NULL COMMENT '删除时间(软删除)',

    INDEX idx_name (name),
    INDEX idx_level (level),
    INDEX idx_city (city),
    INDEX idx_status (status),
    INDEX idx_is_visible (is_visible),
    INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='示范校表';
