/**
 * Test Skeleton for Story 4.5: AttachmentUpload 子组件
 *
 * AUTO-GENERATED by QA Test Design. Dev MUST implement all TODO blocks.
 * Do NOT delete any test case — each maps to a designed scenario.
 * If a scenario is not applicable, change the test to `test.skip` with a reason.
 *
 * Test Design: docs/qa/assessments/4.5-test-design-20260310.md
 * Generated: 2026-03-10
 */

import { describe, test, expect, vi, beforeEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import AttachmentUpload from '../AttachmentUpload.vue'
import ElementPlus from 'element-plus'
import type { AttachmentInfo } from '@/types/content'
import service from '@/utils/request'

// Mock request.ts — the default export is the axios instance
vi.mock('@/utils/request', () => {
  const mockPost = vi.fn()
  return {
    default: {
      post: mockPost,
      get: vi.fn(),
      interceptors: { request: { use: vi.fn() }, response: { use: vi.fn() } },
    },
    get: vi.fn(),
    post: mockPost,
    put: vi.fn(),
    del: vi.fn(),
  }
})

const mockPost = service.post as ReturnType<typeof vi.fn>

function createWrapper(props: Record<string, unknown> = {}) {
  return mount(AttachmentUpload, {
    props: {
      modelValue: null,
      ...props,
    },
    global: {
      plugins: [ElementPlus],
    },
  })
}

function createFile(name: string, size: number, type = 'application/pdf'): File {
  const buffer = new ArrayBuffer(size)
  return new File([buffer], name, { type })
}

// ============================================================
// AttachmentUpload: 文件格式与大小校验
// ============================================================

describe('AttachmentUpload: 文件格式与大小校验', () => {
  test('拒绝非法文件格式 (.exe)', () => {
    // Ref: 4.5-UNIT-014
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('malware.exe', 1024, 'application/x-msdownload')
    expect(vm.beforeUpload(file)).toBe(false)
  })

  test('拒绝非法文件格式 (.zip)', () => {
    // Ref: 4.5-UNIT-014
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('archive.zip', 1024, 'application/zip')
    expect(vm.beforeUpload(file)).toBe(false)
  })

  test('接受 .pdf 文件', () => {
    // Ref: 4.5-UNIT-016
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('doc.pdf', 1024, 'application/pdf')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('接受 .doc 文件', () => {
    // Ref: 4.5-UNIT-016
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('doc.doc', 1024, 'application/msword')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('接受 .docx 文件', () => {
    // Ref: 4.5-UNIT-016
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('doc.docx', 1024, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('接受 .xls 文件', () => {
    // Ref: 4.5-UNIT-016
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('sheet.xls', 1024, 'application/vnd.ms-excel')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('接受 .xlsx 文件', () => {
    // Ref: 4.5-UNIT-016
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('sheet.xlsx', 1024, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('拒绝超过大小限制的文件', () => {
    // Ref: 4.5-UNIT-015
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('large.pdf', 52_428_801, 'application/pdf')
    expect(vm.beforeUpload(file)).toBe(false)
  })

  test('接受恰好等于大小限制的文件', () => {
    // Ref: 4.5-BLIND-BOUNDARY-002
    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const file = createFile('exact.pdf', 52_428_800, 'application/pdf')
    expect(vm.beforeUpload(file)).toBe(true)
  })

  test('accept prop 自定义格式限制', () => {
    // Ref: 4.5-INT-007
    const wrapper = createWrapper({ accept: '.pdf,.doc' })
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const xlsxFile = createFile('sheet.xlsx', 1024)
    expect(vm.beforeUpload(xlsxFile)).toBe(false)
    const pdfFile = createFile('doc.pdf', 1024, 'application/pdf')
    expect(vm.beforeUpload(pdfFile)).toBe(true)
  })

  test('maxSize prop 自定义大小限制', () => {
    // Ref: 4.5-INT-007
    const wrapper = createWrapper({ maxSize: 20 })
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload> & { beforeUpload: (f: File) => boolean }
    const overFile = createFile('big.pdf', 25 * 1024 * 1024, 'application/pdf')
    expect(vm.beforeUpload(overFile)).toBe(false)
    const okFile = createFile('small.pdf', 19 * 1024 * 1024, 'application/pdf')
    expect(vm.beforeUpload(okFile)).toBe(true)
  })
})

// ============================================================
// AttachmentUpload: 上传交互
// ============================================================

describe('AttachmentUpload: 上传交互', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  test('上传成功后显示文件信息', async () => {
    // Ref: 4.5-INT-002
    vi.mocked(mockPost).mockClear()
    mockPost.mockResolvedValueOnce({
      id: 'file-001',
      url: '/uploads/doc.pdf',
      filename: 'doc.pdf',
      size: 2048,
      mime_type: 'application/pdf',
    })

    const wrapper = createWrapper()
    const vm = wrapper.vm as InstanceType<typeof AttachmentUpload>

    // Simulate upload via the exposed upload handler
    // Trigger the upload through el-upload's http-request
    const file = createFile('doc.pdf', 2048, 'application/pdf')
    // Call the internal handleUpload
    await (vm as unknown as { handleUpload: (opts: { file: File }) => Promise<void> }).handleUpload({ file })
    await flushPromises()

    const emitted = wrapper.emitted('update:modelValue')
    expect(emitted).toBeTruthy()
    const lastEmit = emitted![emitted!.length - 1][0] as AttachmentInfo
    expect(lastEmit.fileId).toBe('file-001')
    expect(lastEmit.fileName).toBe('doc.pdf')
    expect(lastEmit.fileSize).toBe(2048)
    expect(lastEmit.fileUrl).toBe('/uploads/doc.pdf')
  })

  test('删除已上传文件', async () => {
    // Ref: 4.5-INT-003
    const attachment: AttachmentInfo = {
      fileId: 'file-001',
      fileName: 'doc.pdf',
      fileSize: 2048,
      fileUrl: '/uploads/doc.pdf',
      mimeType: 'application/pdf',
    }

    const wrapper = createWrapper({ modelValue: attachment })
    await flushPromises()

    // Should show file info with delete button
    expect(wrapper.find('.attachment-upload__file').exists()).toBe(true)

    // Click delete
    await wrapper.find('.el-button--danger').trigger('click')
    const emitted = wrapper.emitted('update:modelValue')
    expect(emitted).toBeTruthy()
    expect(emitted![emitted!.length - 1][0]).toBeNull()
  })

  test('上传失败显示错误和重试', async () => {
    // Ref: 4.5-INT-004
    vi.mocked(mockPost).mockClear()
    mockPost.mockRejectedValueOnce(new Error('Server Error'))

    const wrapper = createWrapper()
    const vm = wrapper.vm as unknown as { handleUpload: (opts: { file: File }) => Promise<void> }
    const file = createFile('doc.pdf', 2048, 'application/pdf')

    await vm.handleUpload({ file })
    await flushPromises()

    expect(wrapper.find('.attachment-upload__error').exists()).toBe(true)
    expect(wrapper.find('.attachment-upload__error-msg').text()).toBe('文件上传失败，请重试')
  })

  test('emit 正确的 attachments 数据格式', async () => {
    // Ref: 4.5-UNIT-017
    vi.mocked(mockPost).mockClear()
    mockPost.mockResolvedValueOnce({
      id: 'f-123',
      url: '/uploads/report.docx',
      filename: 'report.docx',
      size: 10240,
      mime_type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    })

    const wrapper = createWrapper()
    const vm = wrapper.vm as unknown as { handleUpload: (opts: { file: File }) => Promise<void> }
    const file = createFile('report.docx', 10240)

    await vm.handleUpload({ file })
    await flushPromises()

    const emitted = wrapper.emitted('update:modelValue')
    expect(emitted).toBeTruthy()
    const data = emitted![emitted!.length - 1][0] as AttachmentInfo
    expect(data).toEqual({
      fileId: 'f-123',
      fileName: 'report.docx',
      fileSize: 10240,
      fileUrl: '/uploads/report.docx',
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    })
  })
})
