/**
 * Test Skeleton for Story 4.1: 一级栏目管理 — Controller Layer
 *
 * AUTO-GENERATED by QA Test Design. Dev MUST implement all TODO blocks.
 * Do NOT delete any test case — each maps to a designed scenario.
 * If a scenario is not applicable, change the test to @Disabled with a reason.
 *
 * Test Design: docs/qa/assessments/4.1-test-design-20260309.md
 * Generated: 2026-03-09
 */
package com.educp.content.controller;

import com.educp.common.exception.BusinessException;
import com.educp.common.exception.ResourceNotFoundException;
import com.educp.common.handler.GlobalExceptionHandler;
import com.educp.common.security.RoleCheckAspect;
import com.educp.common.security.SecurityConstants;
import com.educp.common.security.UserContextFilter;
import com.educp.content.dto.response.ColumnResponse;
import com.educp.content.dto.response.SubColumnResponse;
import com.educp.content.service.ColumnService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.bean.MockBean;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest({ColumnController.class, PortalColumnController.class})
@Import({GlobalExceptionHandler.class, RoleCheckAspect.class, UserContextFilter.class})
@EnableAspectJAutoProxy
class ColumnControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private ColumnService columnService;

    private static final String ADMIN_COLUMNS_URL = "/v1/columns";
    private static final String PORTAL_COLUMNS_URL = "/v1/portal/columns";

    private ColumnResponse buildSampleResponse(Long id, String name, String code, boolean isSystem) {
        ColumnResponse r = new ColumnResponse();
        r.setId(id);
        r.setName(name);
        r.setCode(code);
        r.setIsSystem(isSystem);
        r.setIsVisible(true);
        r.setSortOrder(1);
        r.setCreatedAt(LocalDateTime.now());
        r.setUpdatedAt(LocalDateTime.now());
        return r;
    }

    // ============================================================
    // AC1: 栏目列表展示 — API Layer
    // ============================================================

    @Nested
    @DisplayName("AC1: 栏目列表 API")
    class AC1_ListApi {

        @Test
        @DisplayName("4.1-INT-001: GET /v1/columns 返回全部栏目")
        void listColumns_returnsAllColumns() throws Exception {
            ColumnResponse col = buildSampleResponse(1L, "首页", "home", true);
            when(columnService.listAll()).thenReturn(List.of(col));

            mockMvc.perform(get(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200))
                    .andExpect(jsonPath("$.data").isArray())
                    .andExpect(jsonPath("$.data[0].name").value("首页"))
                    .andExpect(jsonPath("$.data[0].isSystem").value(true));
        }

        @Test
        @DisplayName("4.1-INT-002: GET /v1/columns 无权限（role=2）返回 403")
        void listColumns_noPermission_returns403() throws Exception {
            mockMvc.perform(get(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "2")
                            .header(SecurityConstants.HEADER_USER_ROLE, "2"))
                    .andExpect(status().isForbidden());
        }

        @Test
        @DisplayName("4.1-INT-003: GET /v1/columns 未认证返回 403")
        void listColumns_unauthenticated_returns403() throws Exception {
            // No headers → UserContext is null → RoleCheckAspect throws ForbiddenException
            mockMvc.perform(get(ADMIN_COLUMNS_URL))
                    .andExpect(status().isForbidden());
        }
    }

    // ============================================================
    // AC2: 栏目排序 — API Layer
    // ============================================================

    @Nested
    @DisplayName("AC2: 栏目排序 API")
    class AC2_SortApi {

        @Test
        @DisplayName("4.1-INT-004: PUT /v1/columns/sort 批量排序成功")
        void sortColumns_validRequest_returns200() throws Exception {
            doNothing().when(columnService).updateSort(any());

            String body = """
                    {"items":[{"id":1,"sortOrder":3},{"id":2,"sortOrder":1}]}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/sort")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200));
        }

        @Test
        @DisplayName("4.1-INT-005: PUT /v1/columns/sort 排序值含负数返回 400")
        void sortColumns_negativeSortOrder_returns400() throws Exception {
            String body = """
                    {"items":[{"id":1,"sortOrder":-1}]}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/sort")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }
    }

    // ============================================================
    // AC3: 系统预置栏目保护 — API Layer
    // ============================================================

    @Nested
    @DisplayName("AC3: 系统预置栏目保护 API")
    class AC3_SystemProtectionApi {

        @Test
        @DisplayName("4.1-INT-006: DELETE /v1/columns/{id} 对系统预置栏目返回 422")
        void deleteColumn_systemColumn_returns422() throws Exception {
            doThrow(new BusinessException("系统预置栏目不可删除，仅可隐藏"))
                    .when(columnService).delete(1L);

            mockMvc.perform(delete(ADMIN_COLUMNS_URL + "/1")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1"))
                    .andExpect(status().isUnprocessableEntity())
                    .andExpect(jsonPath("$.message").value("系统预置栏目不可删除，仅可隐藏"));
        }

        @Test
        @DisplayName("4.1-INT-007: PUT /v1/columns/{id} 对系统预置栏目修改 code 返回 422")
        void updateColumn_systemColumn_changeCode_returns422() throws Exception {
            doThrow(new BusinessException("系统预置栏目代码不可修改"))
                    .when(columnService).update(eq(1L), any());

            String body = """
                    {"code":"new-code"}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/1")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isUnprocessableEntity())
                    .andExpect(jsonPath("$.message").value("系统预置栏目代码不可修改"));
        }

        @Test
        @DisplayName("4.1-INT-008: PUT /v1/columns/{id} 对系统预置栏目修改 name 返回 200")
        void updateColumn_systemColumn_changeName_returns200() throws Exception {
            doNothing().when(columnService).update(eq(1L), any());

            String body = """
                    {"name":"新名称"}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/1")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200));
        }
    }

    // ============================================================
    // AC4: 栏目删除保护 — API Layer
    // ============================================================

    @Nested
    @DisplayName("AC4: 关联内容删除保护 API")
    class AC4_RelatedContentProtectionApi {

        @Test
        @DisplayName("4.1-INT-009: DELETE /v1/columns/{id} 有关联内容返回 422")
        void deleteColumn_withChildren_returns422() throws Exception {
            doThrow(new BusinessException("该栏目下有关联内容，不可删除"))
                    .when(columnService).delete(20L);

            mockMvc.perform(delete(ADMIN_COLUMNS_URL + "/20")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1"))
                    .andExpect(status().isUnprocessableEntity())
                    .andExpect(jsonPath("$.message").value("该栏目下有关联内容，不可删除"));
        }

        @Test
        @DisplayName("4.1-INT-010: DELETE /v1/columns/{id} 栏目不存在返回 404")
        void deleteColumn_notFound_returns404() throws Exception {
            doThrow(new ResourceNotFoundException("栏目", 999L))
                    .when(columnService).delete(999L);

            mockMvc.perform(delete(ADMIN_COLUMNS_URL + "/999")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1"))
                    .andExpect(status().isNotFound());
        }
    }

    // ============================================================
    // AC5: CRUD + 公开 API — API Layer
    // ============================================================

    @Nested
    @DisplayName("AC5: CRUD + 公开 API")
    class AC5_CrudAndPublicApi {

        @Test
        @DisplayName("4.1-INT-011: POST /v1/columns 创建栏目成功")
        void createColumn_validRequest_returns200() throws Exception {
            when(columnService.create(any())).thenReturn(100L);

            String body = """
                    {"name":"测试栏目","code":"test-col","sortOrder":10,"routePath":"/test"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200))
                    .andExpect(jsonPath("$.data").value(100));
        }

        @Test
        @DisplayName("4.1-INT-012: POST /v1/columns 参数校验失败返回 400")
        void createColumn_invalidRequest_returns400() throws Exception {
            String body = """
                    {"name":"","code":"1abc"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("4.1-INT-013: PUT /v1/columns/{id} 更新栏目成功")
        void updateColumn_validRequest_returns200() throws Exception {
            doNothing().when(columnService).update(eq(10L), any());

            String body = """
                    {"name":"更新名称","sortOrder":5}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/10")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200));
        }

        @Test
        @DisplayName("4.1-INT-014: GET /v1/portal/columns 无需认证返回可见栏目列表")
        void portalColumns_noAuth_returnsVisibleColumns() throws Exception {
            ColumnResponse col = buildSampleResponse(1L, "首页", "home", true);
            when(columnService.listVisible()).thenReturn(List.of(col));

            // No auth headers — portal endpoint has no @RequireRole
            mockMvc.perform(get(PORTAL_COLUMNS_URL))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200))
                    .andExpect(jsonPath("$.data").isArray())
                    .andExpect(jsonPath("$.data[0].name").value("首页"));
        }

        @Test
        @DisplayName("4.1-INT-015: GET /v1/portal/columns 隐藏和已删除栏目不在返回结果中")
        void portalColumns_excludesHiddenAndDeleted() throws Exception {
            // Only visible columns returned by service
            ColumnResponse visible = buildSampleResponse(1L, "可见", "visible", false);
            when(columnService.listVisible()).thenReturn(List.of(visible));

            mockMvc.perform(get(PORTAL_COLUMNS_URL))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.data").isArray())
                    .andExpect(jsonPath("$.data.length()").value(1))
                    .andExpect(jsonPath("$.data[0].name").value("可见"));
        }
    }

    // ============================================================
    // Blind Spot Scenarios — API Layer [BLIND-SPOT]
    // ============================================================

    @Nested
    @DisplayName("Blind Spot — Boundary Validation")
    class BlindSpot_Boundary {

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-001: name 空字符串入参")
        void create_emptyName_returns400() throws Exception {
            String body = """
                    {"name":"","code":"valid-code"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-002: name 恰好 50 字符应通过")
        void create_name50Chars_returns200() throws Exception {
            when(columnService.create(any())).thenReturn(1L);
            String name50 = "a".repeat(50);
            String body = String.format("""
                    {"name":"%s","code":"valid-code"}
                    """, name50);

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-003: name 51 字符应拒绝")
        void create_name51Chars_returns400() throws Exception {
            String name51 = "a".repeat(51);
            String body = String.format("""
                    {"name":"%s","code":"valid-code"}
                    """, name51);

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-004: code 以数字开头应拒绝")
        void create_codeStartsWithDigit_returns400() throws Exception {
            String body = """
                    {"name":"测试","code":"1abc"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-005: code 含大写字母应拒绝")
        void create_codeWithUppercase_returns400() throws Exception {
            String body = """
                    {"name":"测试","code":"Home"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-006: sortOrder 为负数应拒绝")
        void create_negativeSortOrder_returns400() throws Exception {
            String body = """
                    {"name":"测试","code":"test","sortOrder":-1}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-007: routePath 恰好 200 字符应通过")
        void create_routePath200Chars_returns200() throws Exception {
            when(columnService.create(any())).thenReturn(1L);
            String path200 = "/" + "a".repeat(199);
            String body = String.format("""
                    {"name":"测试","code":"test","routePath":"%s"}
                    """, path200);

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-BOUNDARY-008: routePath 201 字符应拒绝")
        void create_routePath201Chars_returns400() throws Exception {
            String path201 = "/" + "a".repeat(200);
            String body = String.format("""
                    {"name":"测试","code":"test","routePath":"%s"}
                    """, path201);

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }
    }

    @Nested
    @DisplayName("Blind Spot — Flow & Data")
    class BlindSpot_FlowAndData {

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-FLOW-001: 双击提交 — 唯一性校验阻止重复")
        void create_doubleSubmit_noDuplicate() throws Exception {
            // First call succeeds, second call throws due to name uniqueness
            when(columnService.create(any()))
                    .thenReturn(1L)
                    .thenThrow(new BusinessException("栏目名称已存在"));

            String body = """
                    {"name":"测试","code":"test"}
                    """;

            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk());

            // Simulating second submit (service would reject duplicate)
            mockMvc.perform(post(ADMIN_COLUMNS_URL)
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isUnprocessableEntity());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-CONCURRENCY-002: 删除与编辑并发 — 返回 404")
        void deleteAndEdit_sameColumn_concurrent() throws Exception {
            // If column was deleted before edit, service throws ResourceNotFoundException
            doThrow(new ResourceNotFoundException("栏目", 10L))
                    .when(columnService).update(eq(10L), any());

            String body = """
                    {"name":"修改"}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/10")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isNotFound());
        }

        @Test
        @DisplayName("[BLIND-SPOT] 4.1-BLIND-DATA-003: 公开 API 不暴露 deleted_at/created_by 字段")
        void portalColumns_noSensitiveFields() throws Exception {
            ColumnResponse col = buildSampleResponse(1L, "首页", "home", true);
            when(columnService.listVisible()).thenReturn(List.of(col));

            mockMvc.perform(get(PORTAL_COLUMNS_URL))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.data[0].deletedAt").doesNotExist())
                    .andExpect(jsonPath("$.data[0].createdBy").doesNotExist());
        }
    }

    // ============================================================
    // Story 4.2: 二级栏目管理 — ColumnController 扩展
    // ============================================================

    @Nested
    @DisplayName("Story 4.2: subMenuEnabled 启用开关")
    class Story42_SubMenuEnabled {

        @Test
        @DisplayName("4.2-INT-001: PUT /v1/columns/{id} 更新 subMenuEnabled=true 返回 200")
        void updateColumn_subMenuEnabled_returns200() throws Exception {
            doNothing().when(columnService).update(eq(10L), any());

            String body = """
                    {"subMenuEnabled": true}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/10")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200));
        }

        @Test
        @DisplayName("4.2-INT-001b: PUT /v1/columns/{id} 更新 subMenuEnabled=false 返回 200")
        void updateColumn_subMenuDisabled_returns200() throws Exception {
            doNothing().when(columnService).update(eq(10L), any());

            String body = """
                    {"subMenuEnabled": false}
                    """;

            mockMvc.perform(put(ADMIN_COLUMNS_URL + "/10")
                            .header(SecurityConstants.HEADER_USER_ID, "1")
                            .header(SecurityConstants.HEADER_USER_ROLE, "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200));
        }
    }

    @Nested
    @DisplayName("Story 4.2: 公开 API 含 subColumns")
    class Story42_PortalSubColumns {

        @Test
        @DisplayName("4.2-INT-002: GET /v1/portal/columns 仅在 sub_menu_enabled=1 时含 subColumns")
        void portalColumns_returnsSubColumnsOnlyWhenEnabled() throws Exception {
            ColumnResponse enabledCol = buildSampleResponse(3L, "政策文件", "policy", true);
            enabledCol.setSubMenuEnabled(true);
            SubColumnResponse sub = new SubColumnResponse();
            sub.setId(1L);
            sub.setColumnId(3L);
            sub.setName("国家政策");
            sub.setCode("national-policy");
            sub.setIsSystem(true);
            sub.setSortOrder(1);
            enabledCol.setSubColumns(List.of(sub));

            ColumnResponse disabledCol = buildSampleResponse(4L, "院校风采", "schools", true);
            disabledCol.setSubMenuEnabled(false);
            disabledCol.setSubColumns(Collections.emptyList());

            when(columnService.listVisible()).thenReturn(List.of(enabledCol, disabledCol));

            mockMvc.perform(get(PORTAL_COLUMNS_URL))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.data.length()").value(2))
                    .andExpect(jsonPath("$.data[0].subMenuEnabled").value(true))
                    .andExpect(jsonPath("$.data[0].subColumns").isArray())
                    .andExpect(jsonPath("$.data[0].subColumns.length()").value(1))
                    .andExpect(jsonPath("$.data[0].subColumns[0].name").value("国家政策"))
                    .andExpect(jsonPath("$.data[1].subMenuEnabled").value(false))
                    .andExpect(jsonPath("$.data[1].subColumns").isEmpty());
        }

        @Test
        @DisplayName("4.2-INT-012: GET /v1/portal/columns 无需认证，返回含 subColumns 结构")
        void portalColumns_noAuth_returnsSubColumnsStructure() throws Exception {
            ColumnResponse col = buildSampleResponse(3L, "政策文件", "policy", true);
            col.setSubMenuEnabled(true);
            col.setSubColumns(Collections.emptyList());
            when(columnService.listVisible()).thenReturn(List.of(col));

            mockMvc.perform(get(PORTAL_COLUMNS_URL))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.code").value(200))
                    .andExpect(jsonPath("$.data[0].subMenuEnabled").value(true))
                    .andExpect(jsonPath("$.data[0].subColumns").isArray());
        }
    }
}
